<?php

function bmv_location_pages(): array
{
    return [
        'potsdam' => [
            'name' => 'Potsdam',
            'meta_title' => 'Essen auf Rädern in Potsdam | BMV Menüdienst',
            'meta_description' => 'Essen auf Rädern in Potsdam: warme Mittagsmenüs für alle Stadtteile. BMV liefert täglich frisch, verlässlich und regional.',
            'canonical_path' => '/essen-auf-raedern/potsdam/',
            'hero_badge' => 'Potsdam',
            'hero_heading' => 'Essen auf Rädern in Potsdam mit regionaler Verlässlichkeit.',
            'hero_lead' => 'Von Babelsberg bis Bornstedt: BMV liefert täglich frisch gekochte Menüs in die Landeshauptstadt und verbindet Versorgung mit persönlichem Service.',
            'section_title' => 'Warum Potsdam BMV nutzt',
            'section_intro' => 'Potsdam verlangt in der Versorgung vor allem eines: klare Abläufe. Genau darauf ist unsere regionale Lieferlogik ausgelegt.',
            'coverage' => [
                'Belieferung aller wichtigen Potsdamer Stadtteile',
                'Geeignet für private Haushalte und Angehörigen-Organisation',
                'Kurze Wege zwischen Küche, Disposition und Auslieferung',
            ],
            'highlights' => [
                'Frisch gekocht statt standardisiert angeliefert',
                'Persönliche Abstimmung bei Start, Pause oder Anpassungen',
                'Tägliche Versorgung auch für langfristige Routinen geeignet',
            ],
            'image' => '/assets/images/potsdam-lieferung.jpg',
        ],
        'werder-havel' => [
            'name' => 'Werder (Havel)',
            'meta_title' => 'Essen auf Rädern in Werder (Havel) | BMV Menüdienst',
            'meta_description' => 'Essen auf Rädern in Werder (Havel): täglich warm geliefert direkt vom regionalen Standort in Werder. Persönlich, nah und planbar.',
            'canonical_path' => '/essen-auf-raedern/werder-havel/',
            'hero_badge' => 'Werder (Havel)',
            'hero_heading' => 'Direkt aus Werder geliefert. Regionaler wird Versorgung kaum.',
            'hero_lead' => 'Unser Standort liegt in Werder (Havel). Genau deshalb ist die Versorgung hier besonders nah, schnell abgestimmt und operativ sauber organisiert.',
            'section_title' => 'Der Standortvorteil für Werder',
            'section_intro' => 'Wenn Küche, Disposition und Liefergebiet so nah beieinanderliegen, profitieren Kundinnen und Kunden von besonders kurzen Abstimmungswegen.',
            'coverage' => [
                'Lokale Auslieferung mit besonders kurzen Fahrwegen',
                'Schnelle Abstimmung bei Änderungen oder Rückfragen',
                'Direkte Verbindung zur Kantine und Produktionsküche',
            ],
            'highlights' => [
                'Besonders starke regionale Betreuung',
                'Ideal für Haushalte in Werder und angrenzenden Ortsteilen',
                'Persönlicher Kontakt mit echtem Standortbezug',
            ],
            'image' => '/assets/images/werder-havel-standort.jpg',
        ],
        'umland' => [
            'name' => 'Potsdam-Mittelmark Umland',
            'meta_title' => 'Essen auf Rädern im Umland von Potsdam-Mittelmark | BMV Menüdienst',
            'meta_description' => 'Essen auf Rädern im Umland: BMV beliefert zahlreiche Gemeinden rund um Potsdam und Werder mit frischen Menüs und klaren Abläufen.',
            'canonical_path' => '/essen-auf-raedern/umland/',
            'hero_badge' => 'Potsdam-Mittelmark',
            'hero_heading' => 'Versorgung im Umland ohne Großstadt-Lücke.',
            'hero_lead' => 'Auch außerhalb von Potsdam und Werder liefert BMV warme Menüs in viele Gemeinden. Genau diese regionale Fläche ist Teil unseres Alltagsgeschäfts.',
            'section_title' => 'Für viele Gemeinden direkt relevant',
            'section_intro' => 'Gerade im Umland zählt planbare Versorgung besonders. Deshalb prüfen wir Liefergebiete konkret und nicht nur pauschal.',
            'coverage' => [
                'Lieferung in ausgewählte Gemeinden des Umlands',
                'Geeignet für Haushalte mit etwas größerer Distanz zur Stadt',
                'Gebietsprüfung direkt im Erstkontakt',
            ],
            'highlights' => [
                'Regional organisiert statt zentral abgewickelt',
                'Klare Aussage, ob ein Ort aktuell im Liefergebiet liegt',
                'Versorgung mit denselben Qualitätsstandards wie in Potsdam und Werder',
            ],
            'image' => '/assets/images/umland-lieferung.jpg',
        ],
        'brandenburg-an-der-havel' => [
            'name' => 'Brandenburg an der Havel',
            'meta_title' => 'Essen auf Rädern in Brandenburg an der Havel | BMV Menüdienst',
            'meta_description' => 'Essen auf Rädern in Brandenburg an der Havel: regionale Menüversorgung mit frischer Küche, persönlichem Service und klarer Abstimmung.',
            'canonical_path' => '/essen-auf-raedern/brandenburg-an-der-havel/',
            'hero_badge' => 'Brandenburg an der Havel',
            'hero_heading' => 'Essen auf Rädern für Brandenburg an der Havel – regional gedacht, sauber organisiert.',
            'hero_lead' => 'Für Haushalte in Brandenburg an der Havel ist vor allem wichtig, dass Versorgung nicht kompliziert wird. Genau dafür ist unser Prozess ausgelegt.',
            'section_title' => 'Was in Brandenburg an der Havel zählt',
            'section_intro' => 'Wer eine verlässliche Essensversorgung sucht, braucht nachvollziehbare Abläufe und klare Ansprechpartner statt Plattform-Logik.',
            'coverage' => [
                'Geeignet für private Versorgung und Angehörigenkoordination',
                'Persönliche Abstimmung zu Lieferbarkeit und Starttermin',
                'Frisch gekochte Menüs statt Standardlösungen',
            ],
            'highlights' => [
                'Regionale Nähe zur Versorgung in Westbrandenburg',
                'Direkter Kontakt zu einem operativen Team',
                'Saubere Menüstruktur mit klarer Auswahl',
            ],
            'image' => '/assets/images/essen-auf-raedern-lieferung.jpg',
        ],
        'teltow' => [
            'name' => 'Teltow',
            'meta_title' => 'Essen auf Rädern in Teltow | BMV Menüdienst',
            'meta_description' => 'Essen auf Rädern in Teltow: frische Mittagsmenüs, regional organisiert und verlässlich geliefert von BMV Menüdienst.',
            'canonical_path' => '/essen-auf-raedern/teltow/',
            'hero_badge' => 'Teltow',
            'hero_heading' => 'Tägliche Menüversorgung für Teltow – planbar und persönlich.',
            'hero_lead' => 'In Teltow ist die Nähe zu Berlin hoch, der Bedarf an verlässlicher regionaler Versorgung aber genauso konkret. BMV verbindet beides mit klarer Lieferlogik.',
            'section_title' => 'Warum Teltow ein starkes Einzugsgebiet ist',
            'section_intro' => 'Teltow profitiert von der Nähe zu Potsdam-Mittelmark und vom Bedarf an professionell organisierter häuslicher Versorgung.',
            'coverage' => [
                'Relevant für Seniorenhaushalte und Familienorganisation',
                'Klare Menüauswahl mit transparenter Struktur',
                'Persönliche Abstimmung zum Liefergebiet',
            ],
            'highlights' => [
                'Geeignet für langfristige Versorgungslösungen',
                'Regionale Nähe statt anonymer Dienstleistung',
                'Saubere operative Kommunikation',
            ],
            'image' => '/assets/images/umland-lieferung.jpg',
        ],
        'kleinmachnow' => [
            'name' => 'Kleinmachnow',
            'meta_title' => 'Essen auf Rädern in Kleinmachnow | BMV Menüdienst',
            'meta_description' => 'Essen auf Rädern in Kleinmachnow: warme Mittagsmenüs mit regionalem Service, klarer Abstimmung und frischer Küche.',
            'canonical_path' => '/essen-auf-raedern/kleinmachnow/',
            'hero_badge' => 'Kleinmachnow',
            'hero_heading' => 'Essen auf Rädern in Kleinmachnow mit verlässlichem regionalem Ablauf.',
            'hero_lead' => 'Kleinmachnow braucht keine überladene Plattform, sondern einen Menüdienst, der im Alltag funktioniert. Genau dort liegt die Stärke von BMV.',
            'section_title' => 'Versorgung für Kleinmachnow',
            'section_intro' => 'Gerade in gut angebundenen Wohnlagen ist persönliche Servicequalität oft der entscheidende Unterschied.',
            'coverage' => [
                'Persönliche Erstabstimmung statt Standardformular',
                'Klar strukturierte Menüversorgung für zuhause',
                'Geeignet für kontinuierliche und temporäre Bedarfe',
            ],
            'highlights' => [
                'Frische Küche mit regionalem Hintergrund',
                'Verlässliche Kommunikation bei Änderungen',
                'Nah an Potsdam und dem südwestlichen Berliner Raum',
            ],
            'image' => '/assets/images/umland-lieferung.jpg',
        ],
        'falkensee' => [
            'name' => 'Falkensee',
            'meta_title' => 'Essen auf Rädern in Falkensee | BMV Menüdienst',
            'meta_description' => 'Essen auf Rädern in Falkensee: regionale Menüversorgung mit klaren Abläufen, frischer Küche und persönlicher Abstimmung.',
            'canonical_path' => '/essen-auf-raedern/falkensee/',
            'hero_badge' => 'Falkensee',
            'hero_heading' => 'Für Falkensee zählt Versorgung, die im Alltag wirklich trägt.',
            'hero_lead' => 'BMV organisiert Menüversorgung so, dass sie im Alltag hilft: mit Frische, Verlässlichkeit und einer Lieferlogik, die nachvollziehbar bleibt.',
            'section_title' => 'BMV für Falkensee',
            'section_intro' => 'Im westlichen Berliner Umland profitieren Haushalte besonders von regionaler Organisation und klaren Ansprechpartnern.',
            'coverage' => [
                'Geeignet für Haushalte mit organisiertem Angehörigenkontakt',
                'Verlässliche Menüversorgung mit Auswahlstruktur',
                'Klare Prüfung der Lieferbarkeit vor Start',
            ],
            'highlights' => [
                'Frische Menüs aus regionalem Umfeld',
                'Keine künstlich aufgeblähte Buchungsstrecke',
                'Persönlicher Kontakt statt Support-Kette',
            ],
            'image' => '/assets/images/essen-auf-raedern-lieferung.jpg',
        ],
        'berlin-suedwest' => [
            'name' => 'Berlin Südwest',
            'meta_title' => 'Essen auf Rädern in Berlin Südwest | BMV Menüdienst',
            'meta_description' => 'Essen auf Rädern in Berlin Südwest: regionale Menüversorgung für den südwestlichen Berliner Raum mit frischer Küche und persönlicher Betreuung.',
            'canonical_path' => '/essen-auf-raedern/berlin-suedwest/',
            'hero_badge' => 'Berlin Südwest',
            'hero_heading' => 'Menüversorgung für Berlin Südwest – regional gedacht, nicht großstädtisch anonym.',
            'hero_lead' => 'Auch im Berliner Südwesten ist der Bedarf an persönlicher und verlässlicher Essensversorgung real. BMV bringt dafür regionale Stärke aus Brandenburg mit.',
            'section_title' => 'Warum Berlin Südwest relevant ist',
            'section_intro' => 'Im Übergang zwischen Berlin und Brandenburg zählt besonders, dass Lieferlogik, Kommunikation und Zuständigkeit klar sind.',
            'coverage' => [
                'Geeignet für Angehörige, die Versorgung aus Distanz mitorganisieren',
                'Frische Menüs mit nachvollziehbarer Auswahl',
                'Regionaler Gegenpol zur anonymen Plattformlogik',
            ],
            'highlights' => [
                'Klare Erreichbarkeit im Erstkontakt',
                'Persönliche Betreuung mit echter Zuständigkeit',
                'Starker Fit für den südwestlichen Berliner Raum',
            ],
            'image' => '/assets/images/essen-auf-raedern-lieferung.jpg',
        ],
        'berlin-steglitz' => [
            'name' => 'Berlin Steglitz',
            'meta_title' => 'Essen auf Rädern in Berlin Steglitz | BMV Menüdienst',
            'meta_description' => 'Essen auf Rädern in Berlin Steglitz: warme Mittagsmenüs, frische Küche und direkte Abstimmung mit einem regionalen Lieferpartner.',
            'canonical_path' => '/essen-auf-raedern/berlin-steglitz/',
            'hero_badge' => 'Berlin Steglitz',
            'hero_heading' => 'Essen auf Rädern für Steglitz mit regionaler Handschrift.',
            'hero_lead' => 'Für Haushalte in Steglitz ist oft nicht nur das Essen entscheidend, sondern die Verlässlichkeit dahinter. BMV setzt genau dort an.',
            'section_title' => 'Steglitz als Versorgungsstandort',
            'section_intro' => 'Steglitz verbindet urbane Dichte mit einem hohen Bedarf an planbarer häuslicher Unterstützung. Eine klare Servicearchitektur ist deshalb besonders wichtig.',
            'coverage' => [
                'Frische Menüversorgung für den Berliner Südwesten',
                'Direkte Abstimmung statt mehrstufiger Supportwege',
                'Geeignet für kontinuierliche Alltagsversorgung',
            ],
            'highlights' => [
                'Stark für Familien- und Angehörigenkoordination',
                'Regionale Ausrichtung statt Callcenter-Prozess',
                'Klar strukturierter Start und Betrieb',
            ],
            'image' => '/assets/images/essen-auf-raedern-lieferung.jpg',
        ],
        'berlin-zehlendorf' => [
            'name' => 'Berlin Zehlendorf',
            'meta_title' => 'Essen auf Rädern in Berlin Zehlendorf | BMV Menüdienst',
            'meta_description' => 'Essen auf Rädern in Berlin Zehlendorf: regionale Menüversorgung mit frischer Küche, persönlichem Service und klarer Lieferlogik.',
            'canonical_path' => '/essen-auf-raedern/berlin-zehlendorf/',
            'hero_badge' => 'Berlin Zehlendorf',
            'hero_heading' => 'Für Zehlendorf: persönliche Versorgung statt anonymer Standard.',
            'hero_lead' => 'Zehlendorf braucht keine überinszenierte Food-Plattform, sondern verlässliche Menüversorgung, die im Alltag wirklich funktioniert.',
            'section_title' => 'Was in Zehlendorf zählt',
            'section_intro' => 'Gerade in Wohnlagen mit hohem Qualitätsanspruch wird deutlich, wie wichtig persönliche Betreuung und saubere operative Prozesse sind.',
            'coverage' => [
                'Geeignet für Haushalte mit hohem Anspruch an Zuverlässigkeit',
                'Klare Menülinien und einfache Auswahl',
                'Direkte Kommunikation mit einem regionalen Team',
            ],
            'highlights' => [
                'Frische Küche statt standardisierter Convenience',
                'Regionale Zuständigkeit im Berliner Südwesten',
                'Strukturierte Versorgung mit persönlichem Bezug',
            ],
            'image' => '/assets/images/essen-auf-raedern-lieferung.jpg',
        ],
        'berlin-charlottenburg' => [
            'name' => 'Berlin Charlottenburg',
            'meta_title' => 'Essen auf Rädern in Berlin Charlottenburg | BMV Menüdienst',
            'meta_description' => 'Essen auf Rädern in Berlin Charlottenburg: frische Mittagsmenüs, persönliche Abstimmung und regionale Versorgungskompetenz von BMV.',
            'canonical_path' => '/essen-auf-raedern/berlin-charlottenburg/',
            'hero_badge' => 'Berlin Charlottenburg',
            'hero_heading' => 'Essen auf Rädern für Charlottenburg mit klarer Servicequalität.',
            'hero_lead' => 'Charlottenburg verlangt eine Versorgungslösung, die professionell wirkt und im Alltag einfach bleibt. Genau das bildet BMV regional ab.',
            'section_title' => 'Charlottenburg im Fokus',
            'section_intro' => 'Im westlichen Berlin ist Versorgungsqualität vor allem dann stark, wenn Kommunikation, Menüstruktur und Zuständigkeit zusammenpassen.',
            'coverage' => [
                'Frische Menüs mit regionaler Lieferkompetenz',
                'Geeignet für private Haushalte und Angehörigenorganisation',
                'Klare Start- und Abstimmungsprozesse',
            ],
            'highlights' => [
                'Starke Positionierung für den Berliner Westen',
                'Persönliche Begleitung statt bloßer Vermittlung',
                'Verlässliche Alltagsversorgung mit menschlichem Kontakt',
            ],
            'image' => '/assets/images/essen-auf-raedern-lieferung.jpg',
        ],
    ];
}
